### ISSUE TITLE
熟悉專案架構並提出可改善部分

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#22]
可改善部分請列在下方comment

**Comment by keith222** [comment]
升級 Swift 及第三方套件版本，因為 Apple 常會寄信「建議」上架時程式要是最新版本 Swift...
一些使用 Modal 轉場效果的介面或許可以添加下滑離開的功能，目前是點右上方 X 按鈕離開畫面

**Comment by bbandydd** [comment]
轉場效果去年是美術組希望以這樣的方式呈現
今年等美術組設計完之後會跟我們討論，到時候也可以提出建議

**Comment by bbandydd** [comment]
@Wuchiwei 對於程式, 架構或畫面有任何要提出的建議嗎

**Comment by Wuchiwei** [comment]
UI/UX 方面的意見可能之後再與設計師討論，目前看到一些小問題：

1. 因為專案採用 Storyboard，但目前只有兩個 Storyboard, 且大部分的功能都集中在 `Main.storyboard` 。這對日後 co-work 可能會有一些不方便，容易產生 conflict，建議可以多拆分幾個 storyboard。

2. 如果要長期維護這個專案，可能要考慮建立 Coding Style Doc，以便日後維護。

3. 處理複雜的 UITableView 與 UICollection 方法可能要討論並統一比較好。

**Comment by bbandydd** [comment]
@Wuchiwei OK，提出三點很棒的建議，那我將這些規劃在Sprint2，謝謝
