### ISSUE TITLE
將2018 MOPCON專案build起來

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#23]
確認功能正常，並且無破版
- [x] iOS 模擬器
- [x] iOS 實機

**Comment by keith222** [comment]
這邊測試正常
不過我有升級 Swift 以及第三方套件的版本 還有移動幾個檔案路徑
需要開PR 送上去嗎？

**Comment by bbandydd** [comment]
好的，你開個branch發PR，先assign給我
