### ISSUE TITLE
AppCenter build出一版develop

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#27]
- Quiz.json, BoothMission.json等不能上傳到Github的檔案
  - 可以參考Android Team [appcenter-post-clone.sh](https://github.com/MOPCON/App-Android/blob/develop/appcenter-post-clone.sh)方法
  - 將這些檔案包成secrets.tar.enc，然後build的時候解開

**Comment by chnbohwr** [comment]
hi , here is my command to encrypt file into .enc file

```bash
# compress multiple files into single tar file.
tar -czvf secrets.tar BoothMission.json google-services.json Quiz.json release.keystore
# use environment key to encrypt tar file.
openssl des-cbc -e -k $MOPCON_DES_KEY -in secrets.tar -out secrets.tar.enc
```
