### ISSUE TITLE
改善原有架構

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#28]
@keith222 @Wuchiwei 
- Luke提出這兩點改善地方，我覺得對於專案是有幫助的，所以這個Sprint來做
  - 下週訂個時間來討論，兩位覺得如何

- [x] 因為專案採用 Storyboard，但目前只有兩個 Storyboard, 且大部分的功能都集中在 Main.storyboard。這對日後 co-work 可能會有一些不方便，容易產生 conflict，建議可以多拆分幾個 storyboard
- [x] 處理複雜的 UITableView 與 UICollection 方法可能要討論並統一比較好。

**Comment by keith222** [comment]
訂個時間討論的覺得可以
我自己的話平常週間晚上都有時間 可以討論

**Comment by Wuchiwei** [comment]
根據上次會議的結果，我會再新增 7 個 Storyboard，

- [ ] Agenda.storybard
- [ ] Schedual.storybard
- [ ] Communication.storybard
- [ ] Sponsor.storybard
- [ ] Speaker.storybard
- [ ] Group.storybard
- [ ] News

- 會議中提到的 storyboard reference : https://cocoacasts.com/organizing-storyboards-with-storyboard-references

**Comment by Wuchiwei** [comment]
issue two 請見： #33
