### ISSUE TITLE
研究大地遊戲可能會用到的AR功能

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#35]
- 請研究AR功能的可行性及可做到的地步，以利評估大地遊戲進行方式

**Comment by keith222** [comment]
我這邊有弄出偵測圖片然後顯示 3d model 跟 在偵測出的水平面上放上 3d model

**Comment by bbandydd** [comment]
好的........Android支援度低，還沒借到可支援的手機來測試.......
那可以做到互動的功能嗎？

**Comment by keith222** [comment]
大概會是哪些互動的功能？？

**Comment by bbandydd** [comment]
我也是在亂想，因為大地遊戲還不確定要做什麼
所以現在要嘗試各種可行性
例如像Pokemon GO那樣可以丟球抓他之類的互動、或者是點他會說話跳舞等等
而不是只有單純顯示在畫面上

**Comment by keith222** [comment]
不過像是點他說話跳舞的話是要另外請人做說話跳舞的動作模組出來，App 這邊應該只能做的是將他播放
話說這些功能加上去（假如的話）這樣 App 的大小可能會變大不少......

**Comment by bbandydd** [comment]
嗯嗯 我知道要出3D模型
但是以Mopcon的人手來看，我覺得不會用3D模型，大概就用圖片而已
可以先用圖片點了有音效之類的就好
主要是先測試各種可行性
