### ISSUE TITLE
將功能鈕調整成放在下方Navbar

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-iOS#39]
- 2018版將功能鈕放在首頁中，2019版要將功能調整放在下方Navbar

![螢幕快照 2019-07-08 上午9 27 02](https://user-images.githubusercontent.com/11688424/60778836-148f0280-a16b-11e9-9faf-1cc89832b539.png)

**Comment by bbandydd** [comment]
Sprint6 繼續完成

**Comment by Wuchiwei** [comment]
Reference to [PR#41](https://github.com/MOPCON/App-iOS/pull/41)
